### ISSUE TITLE
SDNEXT / LOADING ERROR

### ISSUE THREAD

**Issue by RGX650** [Carzit/sd-webui-samplers-scheduler#5]
15:23:31-459502 ERROR    Module load: extensions\sd-webui-samplers-scheduler\scripts\load_Seniorious.py: ValueError
 Traceback (most recent call last)
│ C:\AI\SDNEXT\automatic\modules\script_loading.py:21 in load_module                                                   │
│                                                                                                                      │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                           │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                          │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                           │
│ in exec_module:883                                                                                                   │
│ in _call_with_frames_removed:241                                                                                     │
│                                                                                                                      │
│ C:\AI\SDNEXT\automatic\extensions\sd-webui-samplers-scheduler\scripts\load_Seniorious.py:18 in <module>              │
│                                                                                                                      │
│   17                                                                                                                 │
│ ❱ 18 if int(version) >= 6:                                                                                           │
│   19 │   from Seniorious_16 import *                                                                                 │
ValueError: invalid literal for int() with base 10: '#'

**Comment by Carzit** [comment]
I'm so sorry for that.  

The script `load_Seniorious.py` will load the right version of Seniorious according to your sd webui. But I played a trick and used the `CHANGELOG.md` in the root directory to determine your version, which may have caused the above problem. I will fix it later.  

Here is a temporary quick solution: delete the `load_Seniorious.py` file in the `scripts` folder, and then place the corresponding file in this repository into the `scripts` folder according to your SD WebUI version: 
- `Seniorious.py` for version <= 1.5.2
- `Seniorious_16.py` for version >= 1.6.0

**Comment by RGX650** [comment]
i saw you updated sd-webui-samplers-scheduler-for-v1.6.   Thanks a lot, cant wait to try this out !

**Comment by RGX650** [comment]
since we are on this subject, any manner to do the same with this one? i have the same problem with it
https://github.com/hnmr293/sd-webui-sd-webui-DPMPP_2M_Karras_v2
Did you try it?

**Comment by Carzit** [comment]
In fact, the original inspiration for Seniorious came from the repository you mentioned.

**Comment by Carzit** [comment]
in #6, I have fixed some bugs about webui version compatibility. Now you can have another try :)
